#!/usr/bin/python

import sys
import termcolor
from claap_functions import *

commands = {'--usage':print_usage_instructions, '--version':version_info, '--info':info, '--commands':display_command_list, '--random':random_fact, 'tokens':get_tokens, 'types':get_types, 'wordcount':get_word_count, 'uwordcount':get_unique_word_count, 'ttr':get_TTR, 'pos':tag_pos, 'poscounts':get_pos_counts, 'plotfreq':plot_freq_dist, 'mostfreq':get_most_frequent, 'leastfreq':get_least_frequent, 'utterances':list_utterances, 'alu':get_avg_utterance_length, 'lcw':get_content_words, 'lucw':get_unique_content_words, 'lfw':get_function_words, 'lufw':get_unique_function_words, 'cfr':get_content_function_ratio, 'normalize':normalize_text}	

def main():
	if len(sys.argv) == 2 and sys.argv[1] in commands.keys():
		print(commands[sys.argv[1]]())
	elif len(sys.argv) == 3 and sys.argv[1] in commands.keys():
		print(commands[sys.argv[1]](sys.argv[2]))
	elif len(sys.argv) == 4 and sys.argv[1] in commands.keys():
                print(commands[sys.argv[1]](sys.argv[2], sys.argv[3]))
	else:
		print('For a list of available commands, use ' + colored('--commands', 'green') + '.')

if __name__ == "__main__":
    main()
