#!/bin/sh
sudo cp -r ~/Code/CLAAP/claap /usr/bin/claap
sudo chmod 777 /usr/bin/claap
#sudo mkdir /usr/bin/claap_src
sudo cp -r ~/Code/CLAAP/claap_src /usr/bin/
sudo chmod 777 /usr/bin/claap_src
#sudo mkdir /usr/bin/claap_tmp
sudo cp -r ~/Code/CLAAP/claap_tmp /usr/bin/
sudo chmod 777 /usr/bin/claap_tmp
